### ISSUE TITLE
Heroku sleeps after 30min

### ISSUE THREAD

**Issue by williamyeh** [technomile/Heroku-Drupal#2]
Hi, thank you for this great project.
I have deployed a drupal app on heroku for free. 
However, after 30 minutes, free heroku sleeps. Then drupal asks me to reinstall the app.
I'm new at this, can somebody tell me how I can fix this please?
Thanks

**Comment by InderjeetSohal** [comment]
Hi,

You need to overwrite setting.php file from this location https://github.com/technomile/Heroku-Drupal/blob/master/sites/default/settings.php into you heroku app repository but before doing this make .gitignore as empty or reinstall Heroku-Drupal builtpack again.

Thanks

**Comment by williamyeh** [comment]
Thank you so much!
